"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight, FileText, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface FullOrderReportProps {
  reportId: string;
  onClose: () => void;
}

export function FullOrderReport({ reportId, onClose }: FullOrderReportProps) {
  const [page, setPage] = useState(1);

  const itemTotals = [
    { code: "PNL-101", name: '3/4" Marine Plywood 4x8', qty: 320, unit: "Sheet" },
    { code: "PNL-102", name: '1/2" MDF Board 4x8', qty: 260, unit: "Sheet" },
    { code: "HW-201", name: "Soft-Close Cabinet Hinge (Pair)", qty: 980, unit: "Pair" },
    { code: "HW-202", name: "18-inch Drawer Slides (Pair)", qty: 410, unit: "Pair" },
    { code: "FIN-301", name: "White Laminate Sheet 4x8", qty: 120, unit: "Sheet" },
    { code: "ADH-401", name: "Titebond II Wood Glue (1 Gallon)", qty: 65, unit: "Gallon" },
  ];

  return (
    <div className="flex flex-col items-center w-full h-full py-10 animate-in zoom-in-95 duration-300">
      <div className="w-full max-w-4xl bg-white shadow-2xl rounded-sm p-10 flex flex-col gap-8">
        {/* Header */}
        <div className="flex justify-between items-start">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-zinc-400">
              <FileText className="h-4 w-4" />
              <span className="text-[10px] font-bold uppercase tracking-widest">Formal Report</span>
            </div>
            <h1 className="text-2xl font-bold text-zinc-900 tracking-tight">Order Aggregate Report</h1>
          </div>
          <Button onClick={onClose} variant="outline" className="gap-2 border-zinc-200">
            <Check className="h-4 w-4" /> Done
          </Button>
        </div>
        
        <Separator className="bg-zinc-100" />

        <div className="flex-1 min-h-[600px]">
          {page === 1 ? (
            /* Page 1 Summary */
            <div className="space-y-8 fade-in animate-in duration-300">
              <ReportSection title="Report Information">
                <InfoGrid items={[
                  { label: "Report ID", value: reportId },
                  { label: "Generated By", value: "Gustavo Fring" },
                  { label: "Date Generated", value: "December 14, 2025" },
                  { label: "Period", value: "Dec 1 - Dec 7, 2025" },
                ]} />
              </ReportSection>

              <ReportSection title="Report Description">
                <div className="p-4 bg-zinc-50 border border-zinc-100 rounded text-sm text-zinc-600 leading-relaxed italic">
                  "System-generated totals of ordered inventory items within the selected reporting period."
                </div>
              </ReportSection>

              <ReportSection title="Data Scope">
                <ul className="list-disc list-inside text-sm text-zinc-500 space-y-1 px-2">
                  <li>Orders recorded within reporting period</li>
                  <li>Aggregated by item and supplier</li>
                  <li>Excludes cancelled/draft orders</li>
                </ul>
              </ReportSection>
            </div>
          ) : (
            /* Page 2 Tables */
            <div className="space-y-8 fade-in animate-in duration-300">
              <ReportSection title="Item Order Totals">
                <div className="border rounded-md overflow-hidden">
                  <Table>
                    <TableHeader className="bg-zinc-900">
                      <TableRow className="hover:bg-zinc-900 border-none">
                        <TableHead className="text-white font-bold h-9">Code</TableHead>
                        <TableHead className="text-white font-bold h-9">Item Name</TableHead>
                        <TableHead className="text-white font-bold text-center h-9">Total Qty</TableHead>
                        <TableHead className="text-white font-bold text-right h-9 px-6">Unit</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {itemTotals.map((item) => (
                        <TableRow key={item.code} className="border-b border-zinc-50">
                          <TableCell className="text-xs font-mono">{item.code}</TableCell>
                          <TableCell className="text-xs">{item.name}</TableCell>
                          <TableCell className="text-xs text-center font-bold">{item.qty}</TableCell>
                          <TableCell className="text-xs text-right text-zinc-400 px-6">{item.unit}</TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </ReportSection>

              <div className="p-4 bg-zinc-50 border border-zinc-100 rounded text-[10px] grid grid-cols-2 gap-4">
                <div className="flex justify-between border-b pb-1"><span>Items Aggregated</span> <b>6</b></div>
                <div className="flex justify-between border-b pb-1"><span>Suppliers</span> <b>4</b></div>
                <div className="flex justify-between"><span>Report ID</span> <b>{reportId}</b></div>
                <div className="flex justify-between"><span>Snapshot</span> <b>2025-12-14</b></div>
              </div>
            </div>
          )}
        </div>

        {/* Footer Pagination */}
        <div className="flex items-center justify-between pt-6 border-t border-zinc-100">
          <span className="text-[10px] text-zinc-400 uppercase tracking-widest font-bold">
            GRACELINE PRODUCTS INC.
          </span>
          <div className="flex items-center gap-4">
            <Button variant="outline" size="icon" onClick={() => setPage(1)} disabled={page === 1} className="h-8 w-8">
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="text-xs font-bold text-zinc-600">Page {page} of 2</span>
            <Button variant="outline" size="icon" onClick={() => setPage(2)} disabled={page === 2} className="h-8 w-8">
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ReportSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h3 className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">{title}</h3>
      {children}
    </div>
  );
}

function InfoGrid({ items }: { items: { label: string; value: string }[] }) {
  return (
    <Card className="bg-zinc-50 border-none shadow-none">
      <CardContent className="p-4 grid grid-cols-2 gap-y-3 gap-x-8">
        {items.map((item, idx) => (
          <div key={idx} className="flex justify-between text-[11px] border-b border-zinc-100 pb-1.5 last:border-0">
            <span className="text-zinc-400">{item.label}</span>
            <span className="font-bold text-zinc-800">{item.value}</span>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}