"use client";

import { Search, Eye, Download, Trash2, CalendarIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

// Updated mock data with unique IDs for navigation logic
const reportsData = [
  { id: "2025-ORD-AGG-0014", type: "Order Aggregate", date: "2025-01-15", user: "Sarah Mitchell" },
  { id: "2025-INV-STK-0002", type: "Inventory Stock", date: "2025-01-12", user: "Sarah Mitchell" },
  { id: "2025-ORD-AGG-0010", type: "Order Aggregate", date: "2025-01-10", user: "Sarah Mitchell" },
];

interface ReportsViewProps {
  onViewReport: (id: string) => void; // Prop to signal navigation
}

export function ReportsView({ onViewReport }: ReportsViewProps) {
  return (
    <div className="w-full space-y-6 p-6 animate-in fade-in duration-500">
      <h1 className="text-2xl font-bold text-slate-900">Reports</h1>

      {/* Generate Report Form */}
      <Card className="shadow-sm border-slate-200">
        <CardHeader>
          <CardTitle className="text-lg font-semibold text-slate-700">
            Generate a New Report
          </CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-500">Report Type</label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select report type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="order">Order Aggregate</SelectItem>
                <SelectItem value="inventory">Inventory Stock</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-500">Start Date</label>
            <div className="relative">
              <Input type="text" placeholder="mm/dd/yyyy" className="pr-10" />
              <CalendarIcon className="absolute right-3 top-2.5 h-4 w-4 text-slate-400" />
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-500">End Date</label>
            <div className="relative">
              <Input type="text" placeholder="mm/dd/yyyy" className="pr-10" />
              <CalendarIcon className="absolute right-3 top-2.5 h-4 w-4 text-slate-400" />
            </div>
          </div>

          <div className="md:col-span-3">
            <Button className="bg-zinc-900 hover:bg-zinc-800 text-white px-8">
              Generate Report
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Reports Table Section */}
      <Card className="shadow-sm border-slate-200">
        <div className="p-4 flex flex-col md:flex-row justify-end items-center gap-4 border-b">
          <div className="relative w-full md:w-64">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
            <Input placeholder="Search for a report..." className="pl-9 bg-slate-50/50" />
          </div>
          <Select defaultValue="filters">
            <SelectTrigger className="w-[140px] bg-slate-100">
              <SelectValue placeholder="Search Filters" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="filters">Search Filters</SelectItem>
              <SelectItem value="date">By Date</SelectItem>
            </SelectContent>
          </Select>
        </div>
        
        <Table>
          <TableHeader>
            <TableRow className="bg-slate-50/50">
              <TableHead className="font-bold text-slate-900">Report Type</TableHead>
              <TableHead className="font-bold text-slate-900 text-center">Date Generated</TableHead>
              <TableHead className="font-bold text-slate-900 text-center">Generated By</TableHead>
              <TableHead className="font-bold text-slate-900 text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reportsData.map((report) => (
              <TableRow key={report.id} className="hover:bg-slate-50/50 border-b last:border-0">
                <TableCell className="text-sm text-slate-700 font-medium">{report.type}</TableCell>
                <TableCell className="text-sm text-slate-500 text-center">{report.date}</TableCell>
                <TableCell className="text-sm text-slate-500 text-center">{report.user}</TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2 text-slate-400">
                    {/* onClick tells the container to show this specific report ID */}
                    <button 
                      onClick={() => onViewReport(report.id)}
                      className="hover:text-zinc-900 transition-colors p-1"
                      title="View Report"
                    >
                      <Eye className="h-4 w-4" />
                    </button>
                    <button className="hover:text-zinc-900 transition-colors p-1" title="Download">
                      <Download className="h-4 w-4" />
                    </button>
                    <button className="hover:text-red-600 transition-colors p-1" title="Delete">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
}